
package exercise01;
import java.awt.Toolkit;

//KLASH MAINFRAME POU EINAI TO KENTRIKO PANEL
public class MainFrame extends javax.swing.JFrame {
    private HomePage homePage; //DILWSH METAVLITIS GIA THN ARXIKI SELIDA
    private Toolkit thekit; //TO ERGALEIO GIA THN EISAGWGH THS EIKONAS
   
    
    public MainFrame() {
        //DIMIOURGEIA ENOS ANTIKEIMENOU RESERVATIONS H OPOIA KLASH EINAI GIA THN APOTHUKEUSH KAI DIAVASMA TWN ANTIKEIMENWN TWN KRATHSEWN APO ARXEIO
        Reservations re = new Reservations();
        //DIAVASMA APO TO ARXEIO KAI PROSTHIKI STHN ARRAYLIST THS KLASHS TWN KRATHSEWN
        Reservations.uploadReservations();
        thekit = this.getToolkit();
        this.setTitle("Πρόγραμμα Κρατήσεων");
        this.setIconImage(thekit.getImage("reservation.png"));
        initComponents();
        //DIMIOURGEIA ANTIKEIMENOU GIA TO JPANEL THS ARXIKHS SELIDAS
        homePage = new HomePage(this);
       //EISAGWGH THS ARXIKHS SELIDAS STO MAINFRAME KAI DINONTAS TOU WS CARDLAYOUT TO LAYOUT KAI ONOMA Card1  
        getContentPane().add(homePage,"Card1");
        getContentPane().setVisible(true);
        this.setLocationRelativeTo(null);
        pack();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
