
package exercise01;

import java.awt.CardLayout;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

//KLASH GIA THN DHMIOURGEIA TOU PANEL GIA THN NEA KRATHSH
public class NewReservation extends javax.swing.JPanel {
    //DILWSH METAVLITWN KLASHS
    private JFrame frame; //GIA TO MAINFRAME
    private CardLayout cardLayout; //GIA TO LAYOUT
    private Date givenDate; //GIA NA PERNEI THN HMERA APO TO POPUP TOU CHECK IN
    private Person personData; //ANTIKEIMENO PERSON
    private Reservation resData; //ANTIKEIMENO RESERVATION
    private Room room; //ANTIKEIMENO TYPOU DWMATIOU
    private boolean breakfast; //GIA TO PRWINO
    private  Date checkin; //GIA THN HMEROMHNIA AFIXHS
    private  Date checkout; //GIA THN HMEROMHNIA ANAXWRISIS
    private String tel; //GIA TO THLEFWNO
    private CalendarPopUp cal2; //ANTIKEIMENO TOU HMEROLOGIOU GIA THN EPILOGH MERAS ANAXWRISHS
    private CalendarPopUp cal; //ANTIKEIMENO TOU HMEROLOGIOU GIA THN EPILOGH MERAS AFIXHS
    private DisplayReservation disp; //ANTIKEIMENO GIA THN EMFANISH TWN KRATHSEWN
  
    //CONSTRUCTOR POU DEXETE WS ORISMA TO MAINFRAME
    public NewReservation(JFrame frame) {
        givenDate = Calendar.getInstance().getTime(); //ORIZEI THN GIVENDATE WS THN SHMERINH
        this.frame = frame;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        tellField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        breakfCheckBox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        cal1Buttn = new javax.swing.JButton();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        cal2Buttn = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(716, 300));
        setPreferredSize(new java.awt.Dimension(917, 602));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Νέα Κράτηση");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Στοιχεία Πελάτη", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Όνομα");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Τηλέφωνο");

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Επίθετο");

        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });

        lastNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastNameFieldKeyTyped(evt);
            }
        });

        tellField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tellFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(lastNameField)
                    .addComponent(tellField))
                .addGap(0, 210, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tellField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Στοιχεία Κράτησης", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Τύπος Δωματίου");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Μονόκλινο", "Δίκλινο", "Τρίκλινο" }));
        jComboBox1.setSelectedIndex(0);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Πρωινό");

        breakfCheckBox.setOpaque(false);
        breakfCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakfCheckBoxActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Ημερομηνία Άφιξης");

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Ημερομηνία Αναχώρησης");

        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFormattedTextField1.setEnabled(false);

        cal1Buttn.setText("Επιλογή");
        cal1Buttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal1ButtnActionPerformed(evt);
            }
        });

        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField2.setToolTipText("");
        jFormattedTextField2.setEnabled(false);

        cal2Buttn.setText("Επιλογή");
        cal2Buttn.setEnabled(false);
        cal2Buttn.setEnabled(false);
        cal2Buttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal2ButtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(breakfCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(167, 167, 167))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cal1Buttn)
                            .addComponent(cal2Buttn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(breakfCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cal1Buttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cal2Buttn))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        saveButton.setText("Αποθύκευση");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Ακύρωση");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, saveButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, saveButton});

    }// </editor-fold>//GEN-END:initComponents
    //METHODOS GIA OTAN GINETE CLICK TO BOX TOU PRWINOU
    private void breakfCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakfCheckBoxActionPerformed
        breakfast=breakfCheckBox.isSelected();//ANALOGOS DINEI TRUE H FALSE TIMH STO BREAKFAST
    }//GEN-LAST:event_breakfCheckBoxActionPerformed
    //METHODOS GIA NA DWSEI TI THA GINEI AN PATITHEI TO KOUMPH AKYRWSH
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //PAIRNEI TO LAYOUT APO TO MAINFRAMEKAI TO EKXWREI STHN METAVLITH
        cardLayout = (CardLayout) frame.getContentPane().getLayout(); 
        cardLayout.show(frame.getContentPane(),"Card1"); //ALLAZEI THN KARTA KAI VAZEI NA EMFANISTEI H KENTRIKH SELIDA
    }//GEN-LAST:event_jButton2ActionPerformed
    
    //AN PATITHEI TO EPILOGH GIA THN HMERA AFIXHS
    private void cal1ButtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal1ButtnActionPerformed
        //DIMIOURGEI TO POPUP PANEL GIA THN HMERA AFIXHS
        cal = new CalendarPopUp(this,jFormattedTextField1,givenDate);   
      
    }//GEN-LAST:event_cal1ButtnActionPerformed
    //METHODOS GIA THN ENERGOPOIHSH TOU KOUMIOU EPILOGHS ANAXWRISHS KAI NA THESEI APENERGOPOIHMENO THS AFIXHS
    public void enableButton(){
        cal2Buttn.setEnabled(true);
        cal1Buttn.setEnabled(false);
    }
    //METHODOS GIA NA DWSEI THN EPILEGMENH HMEROMHNIA
    public void setGivenDate(Date givenDate){
        this.givenDate= givenDate;
    }
    //METHODOS GIA NA EPISTREPSEI THN EPILEGMENH HMEROMHNIA
    public Date getGivenDate(){
        return givenDate;
    }
    //METHODOS GIA TO AN PATITHEI TO KOUMPI EPILOGHS THS HMEROMHNIAS ANAXWRHSHS
    private void cal2ButtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal2ButtnActionPerformed
        //AN TO POPU DEN EINAI ENERGO THS HMEROMHNIAS AFIXHS KAI AN TO KOUMPI THS HMEROMHNIAS AFIXHS EINAI ANENERGO TOTE
        if(cal1Buttn.isEnabled()==false&&!CalendarPopUp.isActive()){
            cal2 = new CalendarPopUp(this,jFormattedTextField2,cal.getDateS()); //FTIAXNEI TO POPUP GIA THN EPILOGH GIA THN HMEROMHNIA ANAXWRISHS
        }
        
        
    }//GEN-LAST:event_cal2ButtnActionPerformed
    //METHODOS GIA NA GINEI ELEGXOS GIA THN APODOXH SWSTON XARAKTURWN GIA TO THLEFWNO
    private void tellFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tellFieldKeyTyped
        if(tellField.getText().length()==10){//OTAN FTASEI STOUS 10 XARAKTHRES DIAGRAFEI OPOIADHPOTE EISODO
             evt.consume();
        }
        if(!Character.isDigit(evt.getKeyChar())){//AN DEN EINAI PSIFIO DIAGRAFEI TON XARAKTHRA
            evt.consume();
        }
    }//GEN-LAST:event_tellFieldKeyTyped
    //METHODOS GIA THN SWSTH APODOXH TOU XARAKTHRA GIA TO EPITHETO
    private void lastNameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameFieldKeyTyped
         if(!Character.isAlphabetic(evt.getKeyChar())){//AN DEN EINAI GRAMMA TOTE TON DIAGRAFEI
            evt.consume();
        }
    }//GEN-LAST:event_lastNameFieldKeyTyped
    //METHODOS GIA THN SWSTH APODOXH TOU XARAKTHRA GIA TO ONOMA
    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
         if(!Character.isAlphabetic(evt.getKeyChar())){//AN DEN EINAI GRAMMA TOTE TON DIAGRAFEI
            evt.consume();
        }
    }//GEN-LAST:event_nameFieldKeyTyped
    //METHODOS GIA NA EPISTRPSEI AN EINAI SWSTO TO THLEFWNO
    private boolean telIsValid(){
        if(tellField.getText().length()==10){
           tel= tellField.getText();
            return true;
        }
        else{
            return false;
        }
    }
    //METHODOS GIA NA EPISTRPSEI AN EINAI SWSTO TO ONOMA
    private boolean nameIsValid(){
        if(nameField.getText().length()>2){
            return true;
        }
        else{
            return false;
        }
    }
    //METHODOS GIA NA EPISTRPSEI AN EINAI SWSTO TO EPWNUMO
    private boolean lastNameIsValid(){
        if(lastNameField.getText().length()>2){
            return true;
        }
        else{
            return false;
        }
    }
    //METHODOS GIA NA EPISTRPSEI AN EINAI SWSTH H HMEROMHNIA
    private boolean dateIsValid(){
        try{//XRHSIMOPOIW TRY GT MPOREI NA MHN EXEI DOTHEI KAI NA EGYREI EXEPTION THN WRA MESA STHN IF
            if(cal.getDateS()!=null&&cal2.getDateS()!=null){ //AN KAI OI 2 HMEROMHNIES DEN EINAI NULL TOTE EINAI SWSTH
                return true;
            }
        }
        catch(NullPointerException e){
            return false;
        }
        return false;
    }
    //METHODOS GIA OTAN PATITHEI TO KOUMPI APOTHUKEUSH
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(telIsValid()&&nameIsValid()&&lastNameIsValid()&&dateIsValid()){//EXETAZEI AN TA PEDIA EINAI SYMPLHRWMENA SWSTA KAI TOTE
            int check = JOptionPane.showConfirmDialog(this,"Συνέχεια για Αποθύκευση?",null,JOptionPane.OK_OPTION);//EMFANIZEI MINIMA GIA NA SYGOUREPSEI OTI THELOUME NA SUNEXISOUME
            if(check==0){ //AN EINAI NAI H EPILOGH TOTE TO APOTHYUKEUEI KAI PAEI STHN ARXIKH SELIDA
                cardLayout = (CardLayout) frame.getContentPane().getLayout();
                cardLayout.show(frame.getContentPane(),"Card1"); 
                checkin=cal.getDateS();//EISAGEI THN HMEROMHNIA AFIXHS
                checkout=cal2.getDateS();//EISAGEI THN HMEROMHNIA ANAXWRISHS
                personData = new Person(nameField.getText(),lastNameField.getText(),tel);//DHMIOURGEI ENA ANTIKEIMENO ME TA STOIXEIA APO TA STOIXEIA POU EXOUN DOTHEI STO PANEL GIA TO ATOMO
                resData = new Reservation(personData,(new Room(jComboBox1.getSelectedIndex()+1)),breakfast,checkin,checkout);//DHMIOURGEI ENA ANTIKEIMENO ME TA STOIXEIA APO TA STOIXEIA POU EXOUN DOTHEI STO PANEL KAI TOU ATOMOU GIA THN KRATHSH 
                Reservations.setReservation(resData); //PROSTHETH THN KRATHSH STIS KRATHSEIS
                Reservations.saveReservations();//APOTHYKEUEI TIS KRATISEIS STO ARXEIO
            
            }
           
        }
        else{//AN DEN EXEI EPILEXEI OLA TA APARAITHTA STOIXEIA TOTE EMFANIZEI TO MINIMA
            JOptionPane.showMessageDialog(this,"Παρακαλώ καταχωρήστε σωστά τα στοιχεία","Σφάλμα",JOptionPane.ERROR_MESSAGE);
          
        }
    }//GEN-LAST:event_saveButtonActionPerformed
    //METHODOS GIA THN EPILOGH TOU TYPOU DWMATIOY 
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        room= new Room(jComboBox1.getSelectedIndex());//DHMIOURGIA KAI APOTHYKEYSH THS TIMHS TYPOY DWMATIOU APO TO JcOMBObOX
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox breakfCheckBox;
    private javax.swing.JButton cal1Buttn;
    private javax.swing.JButton cal2Buttn;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField tellField;
    // End of variables declaration//GEN-END:variables
}
