
package exercise01;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

//KLASH GIA THN DHMIOURGEIA TOU JPANEL POU THA TO EISAGOUME SE ENA JDialog TO DIAL SYGKEKRIMENA GIA THN ANAZHTHSH VASH KAPOIOU KRITHRIOU
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     */
    //CONSTRUCTOR THS KLASHS
    public SearchPanel() {
        //KALSESMA THS METHODOU POY THA DIMIOYRGEI TO JPANEL
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxS = new javax.swing.JComboBox<>();
        jSearchButton = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Αναζήτηση Κράτησης");

        jLabel2.setText("Αναζήτηση βάση με το");

        jLabel3.setText("Εισαγωγή στοιχείου ");

        jComboBoxS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Όνομα", "Επώνυμο", "Τηλέφωνο", "Ημερομηνία Άφιξης" }));
        jComboBoxS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSActionPerformed(evt);
            }
        });

        jSearchButton.setText("Αναζήτηση");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSearchButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jFormattedTextField1)
                                    .addComponent(jComboBoxS, 0, 150, Short.MAX_VALUE))
                                .addGap(72, 72, 72)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField1)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jSearchButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    //METHODOS H OPOIOA OTAN THA TROPOPOIEITAI MIA EPILOGH APO THS DIATHESIMES TOY KRITHRIOU TOTE THA KANEI TA APARAITHTA
    private void jComboBoxSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSActionPerformed
        //ELEGXEI AN EXEI PAREI THN EPILOGH HMEROMHNIAS KAI TOTE ALLAZEI TO FORMAT TOU JFORMATTEDTEXTFIEL EKEI POU EISAGOUME TA DEDOMENA NA EINAI SE MOFH HMEROMHNIAS
        if(jComboBoxS.getSelectedIndex()==3){
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField1.setText("");
       }
       else{//ALLIWS TO THETH XWRIS KAPOIO FORMATTER
           jFormattedTextField1.setFormatterFactory(null);
           jFormattedTextField1.setText("");
       }
    }//GEN-LAST:event_jComboBoxSActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
      
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed
    //METHODOS H OPOIA KATHE FORA POU PATIETE KAPOIO PLHKTRO MESA STO JFORMATTEDTEXT FIELD TOTE THA PAREXEI ENAN ELEGXO
    private void jFormattedTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyTyped
        //EPILOGH TI THA KANEI ANALOGOS ME TO POIO KRITHRIO EXOUME EPILEXEI
        switch(jComboBoxS.getSelectedIndex()){
            //GIA TO ONOMA
            case 0:
            //GIA  TO EPWNUMO EPEIDH KAI TA 2 EXOUN MONO GRAMMATA TOTE DEN VAZOUME BREAK GIA NA ELAXISTOPOIHSOUME TON KWDIKA ALA STO EPWNUMO AN VRETHEI XARAKTHRAS MH ALFARITHMITIKO TOTE DEN TON KRATA
            case 1:
            if(!Character.isAlphabetic(evt.getKeyChar())){
                evt.consume();
            }
            break;
            //GIA TO THLEFWNO
            case 2:
                //AN DEN EINAI PSIFIO TOTE DEN TO KRATAEI
                if(!Character.isDigit(evt.getKeyChar())){
                    evt.consume();
                 }
                else if(jFormattedTextField1.getText().length()>9){//KAI AN EXOUN HDH EISAXTHEI 10 XARAKTHRES TOTE DEN DEXETE ALLON
                   evt.consume();
                }
                break;
                //KAI GIA THN HMEROMHNIA GIA NA MHN PERNEI ALLOUS XARAKTHRES EKTOS APO PSIFIA KAI TON /
            case 3:
                if(!Character.isDigit(evt.getKeyChar())&&(evt.getKeyChar()!='/')){
                    evt.consume();
                }
                break;
            
        }
    }//GEN-LAST:event_jFormattedTextField1KeyTyped
    //METHODOS GIA TO TI THA GINETE OTAN THA PATITHEI TO KOUMPI THS ANAZHTHSHS
    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        boolean find=false; //METAVLITI GIA TO AN EXEI VRETHEI KAPOIA KRATHSH
        //STRING BUILDER GIA THN DHMIOURGEIA TOU NEOU TITLOU GIA TO JPANEL DISPLAYRESERVATION ANALOGOS ME TO THN EPILOGH
        StringBuilder title = new StringBuilder(); 
        title.append("Κρατήσεις ");
        //DHMIOURGEIA ANTIKEIMENOU ARRAYLIST TUPOU RESERVATION GIA THN APOTHUKEUSH OSWN KRATHSEWN EXOUN VRETHEI
        ArrayList<Reservation> findRes=new ArrayList<>();
        if(jFormattedTextField1.getText().equals("")){//ELEGXEI AN DEN EINAI KENO TO PEDIO POU EISAGOUME TA DEDOMENA KAI AN NAI STELNEI KATALHLO MINIMA
            JOptionPane.showMessageDialog(this,"Παρακαλώ εισήγασγε το στοιχείο προς αναζήτηση","Σφάλμα",JOptionPane.ERROR_MESSAGE);
        }
        else{//ALLIWS SYNEXIZEI GIA THN ANAZITISI
            //EPILEGEI ANALOGOS TO KRITHRIO EXEI EPILEXTHEI
            switch(jComboBoxS.getSelectedIndex()){
                //GIA TO ONOMA
                case 0:
                    //EPANALIPSI GIA OLES TIS KRATHSEIS THS ARRAYLIST THS KLASHS RESERVATIONS POU EXEI TIS SUNOLIKES KRATHSEIS
                    for(Reservation a :Reservations.getReservations()){
                        //AN VRETHEI KAI TO EXOUME VALEI NA MHN XREIAZETAI EPALEXH SWSTA TO ONOMA
                        if(a.getPersonData().getName().equalsIgnoreCase(jFormattedTextField1.getText())){
                            
                            //METATROPH THS SUMVOILOSEIRAS TOU ONOMATOS ME TO 1O GRAMMA KEFALAIO KAI TA ALLA MIKRA
                            StringBuilder surName = new StringBuilder();
                            surName.append(a.getPersonData().getName().toLowerCase());
                            surName.setCharAt(0,Character.toUpperCase(surName.charAt(0)));
                            findRes.add(a);
                            //EISAGEI TO ONOMA STON TITLO KAI ME REPLACE GT MPOREI NA VREI PANW APO MIA KRATHSEIS ME TO IDIO ONOMA
                            title.replace(10,title.length(),"με το όνομα "+surName);
                            find=true;//KANEI THN METAVLITI TRUE
                        }
                  
                    }
                    //SE PERIPTWSH POU DEN VREI TO ONOMA SE KRATHSH TOTE EMFANIZEI KATALHLO MINIMA
                    if(!find){
                        JOptionPane.showMessageDialog(this,"Δεν βρέθηκε καμία κράτηση με αυτό το όνομα","Ανεπιτυχής Εντοπισμός",JOptionPane.INFORMATION_MESSAGE); 
                    }
                    break;
                //ANAZHTHSH ME EPWNUMO
                case 1:
                    //EPANALIPSI GIA OLES TIS KRATHSEIS THS ARRAYLIST THS KLASHS RESERVATIONS POU EXEI TIS SUNOLIKES KRATHSEIS
                    for(Reservation a :Reservations.getReservations()){
                        if(a.getPersonData().getLastName().equalsIgnoreCase(jFormattedTextField1.getText())){
                             //METATROPH TOU STRING TOU EPWNUMOU ME TO 1O GRAMMA KEFALAIO KLAI TA YPOLOIPA MIKRA
                            StringBuilder LastName = new StringBuilder();
                            LastName.append(a.getPersonData().getLastName().toLowerCase());
                            LastName.setCharAt(0,Character.toUpperCase(LastName.charAt(0)));
                            findRes.add(a);
                            title.replace(10,title.length(),"με το επώνυμο "+LastName);//PROSTHIKI TOU EPWNUMOU STON TITLO 
                            find=true; //AN EXEI VRETHEI
                        }
                  
                    }
                    //SE PERIPTWSH POU DEN VREI TO ONOMA SE KRATHSH TOTE EMFANIZEI KATALHLO MINIMA
                    if(!find){
                        JOptionPane.showMessageDialog(this,"Δεν βρέθηκε καμία κράτηση με αυτό το επίθετο","Ανεπιτυχής Εντοπισμός",JOptionPane.INFORMATION_MESSAGE); 
                    }
                    break;
                //ANAZHTHSH ME TO THLEFWNO
                case 2:
                    //EPANALIPSI GIA OLES TIS KRATHSEIS THS ARRAYLIST THS KLASHS RESERVATIONS POU EXEI TIS SUNOLIKES KRATHSEIS
                    for(Reservation a :Reservations.getReservations()){
                        if(a.getPersonData().getTel().equals(jFormattedTextField1.getText())){
                            findRes.add(a);
                            title.replace(10,title.length(),"με το τηλέφωνο "+a.getPersonData().getTel());
                            find=true;
                        }
                    
                    } 
                    //SE PERIPTWSH POU DEN VREI TO ONOMA SE KRATHSH TOTE EMFANIZEI KATALHLO MINIMA
                    if(!find){
                        JOptionPane.showMessageDialog(this,"Δεν βρέθηκε καμία κράτηση με αυτό τον αριθμό τηλεφώνου","Ανεπιτυχής Εντοπισμός",JOptionPane.INFORMATION_MESSAGE); 
                    }
                    break;
                //HMEROMHNIA
                case 3:
                    //PROSTHETEI TON FORMATER STO PEDIO EISAGWSHS ALLA AN DEN EINAI TA STOIXEIA STHN MORSH POU TO EXOUME THESEI TOTE EGUREI EXEPTION KAI ENHMERWNEI TON XRHSTH NA DWSEI STHN SWSTH MORFH
                    try {
                        jFormattedTextField1.commitEdit();
                    } catch (ParseException ex) {
                        JOptionPane.showMessageDialog(this,"Παρακαλώ εισήγασγε την ημερομηνία με την μορφή HH/MM/EEEE","Σφάλμα",JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                    //EPANALIPSI GIA OLES TIS KRATHSEIS THS ARRAYLIST THS KLASHS RESERVATIONS POU EXEI TIS SUNOLIKES KRATHSEIS
                    for(Reservation a :Reservations.getReservations()){
                        if(formatDate(a.getCheckIn()).equals(jFormattedTextField1.getText())){
                            findRes.add(a);
                            title.replace(10,title.length(),"με την ημερομηνία "+formatDate(a.getCheckIn()));
                            find=true;
                        }
                   
                    }
                    //SE PERIPTWSH POU DEN VREI TO ONOMA SE KRATHSH TOTE EMFANIZEI KATALHLO MINIMA
                    if(!find){
                       JOptionPane.showMessageDialog(this,"Δεν βρέθηκε καμία κράτηση με αυτή την ημερομηνία","Ανεπιτυχής Εντοπισμός",JOptionPane.INFORMATION_MESSAGE); 
                    }
                    break;
             
                }
            //ELEGXEI AN EXEI VREI PANW APO MIA KRATHSEIS ME AUTO TO KRITHRIO
            if(findRes.size()>1){
                findMore(findRes,title.toString());
            }
            else if(findRes.size()==1){//ELEGXEI AN EXEI VREI MIA KRATHSH ME AUTO TO KRITHRIO
                findSet(findRes,title.toString());
            }
            Dial.closeDialog();//KLEINEI TO JDialog 
      
        }
    }//GEN-LAST:event_jSearchButtonActionPerformed
    //METHODOS GIA THN TROPOPOIHSH TOU FORMAT THS HMEROMHNIA WS HMERA MHNAS XRONOS
    private static String formatDate(Date date){
        SimpleDateFormat DateFor = new SimpleDateFormat("d/M/yy"); //DHMIOURGIA TOU FORMAT
        Calendar al= Calendar.getInstance(); //DIMIOURGEIA ANTIKEIMENOU CALENDAR KAI ARXIKOPOIHSH TOU ME THN TIMH THS SHMERINHS MERAS
        al.setTime(date); //THETH THN HMERA HMEROMHNIA ME AUTH POU EXEI PAREI H METHODOS WS ORISMA
        return DateFor.format(al.getTime()); //EPISTREFEI FORMARISMNH THN HMERA
    }
    
    //METHODOS GIA TO TI THA KANEI AN EXEI VREI PANW APO MIA KRATHSEIS ME AUTO TO STOIXEIO
    private void findMore(ArrayList<Reservation> findRes,String title){//DEXETAI TIS KRATHSEIS POU VRYKE KATHOS KAI TON TITLO
        int optionsSize=findRes.size()+1; //METAVLITI POU KRATAEI TO SYNOLO TWN KARATHSEWN KAI TIS PROSTHETH ENA GIA NA EXEI KAI THN EPILOGH EPILOGH OLWN
          Object[] options = new Object[optionsSize]; //DHMIOURGEIA OBJECT GIA THN EPILOGH TWN EPILOGWN TON KRATHSEWN POU VRETHIIKAN
          options[0] = "ΌΛΕΣ";//THETH WS PRWTH EPILOGH TO NA EPISTREPSEI KAI NA EMFANISEI OLES OSES EXEI VREI
          //KAI META DHMIOURGEI NEA OPTION ANALOGOS ME TIS KRATHSEIS
          for(int i=0;i<findRes.size();i++){
              options[i+1] = findRes.get(i);
          }
          
          //EMFANISH TOY DIALOGOY GIA THN EPILOGH KAPOIAS KRATHSEIS H OLWN
          Object selectedOpt =JOptionPane.showInputDialog(this,"Επέλεξε πια απο τις  κρατήσεις επιθυμείς να δείς","Βρέθηκαν Περισσότερες απο μία κρατήσεις",JOptionPane.QUESTION_MESSAGE,null, options,null);
          if(selectedOpt!=null){//ELEGXEI AN EXEI DWSEI EPILOGH O XRHSTHS
            if(selectedOpt=="ΌΛΕΣ"){//ELEGXEI AN EINAI OLWS TOTE KALEI THN METHODO APO THN KLASH DisplayReservation GIA NA THESEI TON PINAKA OLES TIS TIMES POU VRYKE
               DisplayReservation.setTable(findRes);
               
            }
            else{//ALLIWS KATHARIZEI THN ARRAYLIST PROSTHETEI THN EPILEGMENH KRATHSH KAI KALESMA GIA THN EISAGWGH THS KRATHSHS PROS EMFANISH
              findRes.clear();
              findRes.add((Reservation)selectedOpt);
              DisplayReservation.setTable(findRes);
            }
            
            DisplayReservation.setTitle(title); //THETH TWN NEO TITLO STHN KLASH POU EMFANIZEI TIS KRATISEIS
            }
    }
    //METHODOS GIA TO AN VREI MONO MIA KRATHSH ME TO DOSMENO STOIXEIO
    private void findSet(ArrayList<Reservation> findRes,String title){ 
        DisplayReservation.setTable(findRes);
        DisplayReservation.setTitle(title);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxS;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jSearchButton;
    // End of variables declaration//GEN-END:variables
}
