//DIONYSIOS THEODOSIS AM:321/2015066 2H OMADIKH KATANEMHMENA
package clientgui;

import shared.FlightBooking;//H KLASH GIA THN PTHSH POU THA KLEISTEI
import shared.FlightService;//H KLASH POU EINAI TO INTERFACE GIA TO RMI
import shared.FlightSearchCrit;//H KLASH GIA THN ANAZHTHSH PTHSHS
import java.awt.CardLayout; 
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.rmi.RemoteException;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import static mytools.RemoveComponents.*; //H KLASH GIA THN DIAGRAFH COMPONENTS KAI UPDADE TOU FRAME
import calendar.CalendarPopUp; //H KLASH GIA THN DHMIOURGIA TOU POPUP HMEROLOGIOU
import javax.swing.JOptionPane;
import java.awt.Toolkit;

//KLASH TO MAINFRAME
public class MainJFrame extends javax.swing.JFrame {
    private static  String[] listOfLocations;       //ENAS PINAKAS STRING POU THA PERIEXEI TIS POLHS TWN PTHSEWN
    private Date givenDate;                         //GIA THN EPILEGMENH HMERA 
    private CalendarPopUp calendarArrival;          //ANTIKEIMENO TOU HMEROLOGIOU GIA THN EPILOGH MERAS ANAXWRISHS
    private CalendarPopUp calendarDeparture;        //ANTIKEIMENO TOU HMEROLOGIOU GIA THN EPILOGH MERAS AFIXHS  
    private boolean isOneWay;                       //METAVLITI POU ELEGXEI AN EINAI ONEWAY TRIP
    private CardLayout cardLayout;                  //GIA TO LAYOUT
    private FlightSearchCrit flight;                //METAVLITH GIA TA STOIXEIA ANAZHTHSHS PTHSHS
    private String[] airportNames;                  //METAVLITI PINAKA STRING GIA TIS POLEIS POU EXOUN PTHSEIS
    private static FlightService flightService;     //METAVLITI GIA THN SUNDESH MESW RMI
    private List<FlightBooking> flights;            //METAVLI POU KRATAEI WLES TIS PTHSEIS POU YPARXOUN PROS KRATH
    private Toolkit thekit;                         //TO ERGALEIO GIA THN EISAGWGH THS EIKONAS
    
    // O CONSTRUCTOR TOU FRAME POU DEXETAI THN METAVLITI THS SYNDESHS
    public MainJFrame(FlightService flightService) throws RemoteException {
        thekit = this.getToolkit(); 
        this.setTitle("Αεροπορικά Εισιτήρια"); //DINOUME TITLO STO FRAME
        this.setIconImage(thekit.getImage("icons8-booking-64.png")); //DINOUME ICON STO FRAME
         MainJFrame.flightService= flightService; //ARXIKOPOIHSH THS METAVLITIS GIA THN SYNDESH TOU RMI
         try {
            airportNames = flightService.getAirportNames();//KALSEMA THS SYNARTHSHS GIA THN LIPSI TON ONOMATWN TWN POLEWN APO TON SERVER
        } catch (RemoteException |NullPointerException ex) {//ELEGXOS GIA EXEPTION POU MPOREI NA DHMIOURGHTHOUN
            if(ex.getMessage() != null && (ex.getMessage().contains("Connection refused") || ex.getMessage().contains("No route to host"))){//EXETAZEI AN EINAI APO MH SYNDESH TOU SERVER
                throw new RemoteException("Server2 disconected ");//PETAEI NEO EXCEPTION GIA NA TO DIAXEIRISTH H MAIN
            }
            
        }
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());//THETW NA EXEI TO FRAME KAI OLA TA SWINGS  THN MORFH TOU LEITOURGIKOU
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
       
       listOfLocations= airportNames;//ARXIKOPOIW THN LISTA ME TIS POLEIS 
       givenDate = Calendar.getInstance().getTime(); //THETW THN MERA WS THN SHMERINH
       initComponents(); //METHODOS GIA THN ARXIKOPOIHSH TOU FRAME
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        searchPanel1 = new javax.swing.JPanel();
        searchTitle = new javax.swing.JLabel();
        criteriaPanel = new javax.swing.JPanel();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        departureDLabel = new javax.swing.JLabel();
        returnDLabel = new javax.swing.JLabel();
        passengersLabel = new javax.swing.JLabel();
        roundTripRadioButton = new javax.swing.JRadioButton();
        oneWayRadioButton = new javax.swing.JRadioButton();
        searchButton = new javax.swing.JButton();
        passComboBox = new javax.swing.JComboBox<>();
        fromComboBox = new javax.swing.JComboBox<>();
        toComboBox = new javax.swing.JComboBox<>();
        departureDayButton = new javax.swing.JButton();
        returnDayButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        bookingPanel = new javax.swing.JPanel();
        bookingTitlePanel = new javax.swing.JPanel();
        bookingTitleLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        buttonGroup1.add(roundTripRadioButton);
        buttonGroup1.add(oneWayRadioButton);
        buttonGroup1.setSelected(roundTripRadioButton.getModel(),true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(new java.awt.CardLayout());

        searchPanel1.setForeground(new java.awt.Color(153, 204, 255));
        searchPanel1.setMinimumSize(new java.awt.Dimension(1007, 608));

        searchTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        searchTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchTitle.setText("Αναζήτηση Πτήσης");
        searchTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        criteriaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Πτήσεις", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        fromLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fromLabel.setText("Από");

        toLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toLabel.setText("Πρός");

        departureDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        departureDLabel.setText("Αναχώρηση");

        returnDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        returnDLabel.setText("Επιστροφή");

        passengersLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passengersLabel.setText("Επιβάτες");

        roundTripRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roundTripRadioButton.setText("Με επιστροφή");
        roundTripRadioButton.setFocusable(false);
        roundTripRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundTripRadioButtonActionPerformed(evt);
            }
        });

        oneWayRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oneWayRadioButton.setText("Απλό");
        oneWayRadioButton.setFocusable(false);
        oneWayRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneWayRadioButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Αναζήτηση ");
        searchButton.setFocusable(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        passComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        fromComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(airportNames));
        fromComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromComboBoxActionPerformed(evt);
            }
        });

        toComboBox.setModel(setMod());
        toComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toComboBoxActionPerformed(evt);
            }
        });

        departureDayButton.setBackground(new java.awt.Color(255, 255, 255));
        departureDayButton.setText("Ημερολόγιο");
        departureDayButton.setFocusable(false);
        departureDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureDayButtonActionPerformed(evt);
            }
        });

        returnDayButton.setBackground(new java.awt.Color(255, 255, 255));
        returnDayButton.setText("Ημερολόγιο");
        returnDayButton.setFocusable(false);
        returnDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnDayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout criteriaPanelLayout = new javax.swing.GroupLayout(criteriaPanel);
        criteriaPanel.setLayout(criteriaPanelLayout);
        criteriaPanelLayout.setHorizontalGroup(
            criteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criteriaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(criteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(passComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fromComboBox, 0, 209, Short.MAX_VALUE)
                        .addComponent(fromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(departureDayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(departureDLabel)
                    .addComponent(passengersLabel)
                    .addGroup(criteriaPanelLayout.createSequentialGroup()
                        .addComponent(roundTripRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oneWayRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(criteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDLabel)
                    .addComponent(toComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnDayButton, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addContainerGap())
        );

        criteriaPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {oneWayRadioButton, roundTripRadioButton});

        criteriaPanelLayout.setVerticalGroup(
            criteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criteriaPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(criteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roundTripRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oneWayRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(criteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromLabel)
                    .addComponent(toLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(criteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toComboBox)
                    .addComponent(fromComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(criteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureDLabel)
                    .addComponent(returnDLabel))
                .addGap(9, 9, 9)
                .addGroup(criteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDayButton))
                .addGap(18, 18, 18)
                .addComponent(passengersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(criteriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(148, 148, 148))
        );

        criteriaPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {fromLabel, toLabel});

        criteriaPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {oneWayRadioButton, roundTripRadioButton});

        javax.swing.GroupLayout searchPanel1Layout = new javax.swing.GroupLayout(searchPanel1);
        searchPanel1.setLayout(searchPanel1Layout);
        searchPanel1Layout.setHorizontalGroup(
            searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanel1Layout.createSequentialGroup()
                        .addGap(0, 201, Short.MAX_VALUE)
                        .addComponent(criteriaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 202, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchPanel1Layout.setVerticalGroup(
            searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(criteriaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        MainPanel.add(searchPanel1, "card2");

        bookingPanel.setLayout(new javax.swing.BoxLayout(bookingPanel, javax.swing.BoxLayout.Y_AXIS));

        bookingTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bookingTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingTitleLabel.setText("Κράτηση Πτήσης");

        javax.swing.GroupLayout bookingTitlePanelLayout = new javax.swing.GroupLayout(bookingTitlePanel);
        bookingTitlePanel.setLayout(bookingTitlePanelLayout);
        bookingTitlePanelLayout.setHorizontalGroup(
            bookingTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingTitlePanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(bookingTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                .addContainerGap())
        );
        bookingTitlePanelLayout.setVerticalGroup(
            bookingTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bookingPanel.add(bookingTitlePanel);

        jScrollPane3.setViewportView(bookingPanel);

        MainPanel.add(jScrollPane3, "card6");

        getContentPane().add(MainPanel, "card3");

        jMenu1.setText("Μενού");

        jMenuItem1.setText("Αναζήτηση Πτήσης");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roundTripRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundTripRadioButtonActionPerformed
        isOneWay=false;//ELEGXOSAN EPILEXTHEI ME EPISTROFH 
    }//GEN-LAST:event_roundTripRadioButtonActionPerformed
    //METHODOS GIA TO AN PATITHEI H ANAZHTHSH
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        //ELEGXEI AN YPARXEI SYNDESH ME TON SERVER
        try{
            flightService.dummyMethod();
        }
        catch (RemoteException  | NullPointerException ex) {//GIA NA PIASEI TO EXCEPTION POU PROKALEITAI APO THN MH EPIKOINWNIA ME TON SERVER
            JOptionPane.showMessageDialog(null, "Η σύνδεση με τον server χάθηκε το πρόγραμμα θα τερματίσει",null,JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
        //ELEGXEI AN TO POPUP EINAI APENERGOPOIHMENO KATHWS KAI AN EXOUN EPILEXXTHEI MERES
        if(!CalendarPopUp.isActive()&&calendarDeparture!=null){
            RoundTripPanel roundTrip; //DILWSH METAVLITHS GIA TO PANEL TWN PTHSEWN ME EPISTROFH
            OneWayPanel oneWayPanel;  //DILWSH GIA TO PANEL TWN PTHSEWN MONHS DIADROMHS
            
            //MESA SE TRY CATCH GIATI MPOREI NA MHN YPARXEI EPIKOINWNIA ME TON SERVER THS VASHS 
            try {
                if(isOneWay){//ELEGXEI AN EINAI MONHS DIADROMHS
                    //DHMIOURGEI TO ANTIKEIMENO GIA THN  PTHSH
                    flight = new FlightSearchCrit(fromComboBox.getSelectedItem().toString(),toComboBox.getSelectedItem().toString(),
                            calendarDeparture.getDateS().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),Integer.parseInt(passComboBox.getSelectedItem().toString()));
                    //STELNEI STON SERVER TA STOIXEIA GIA THN ANAZHTHSH THS PTHSHS KAI PERNEI PISW OLES TIS PTHSEIS POU VRETHIKAN
                    flights=flightService.searchFlights(flight); 
                    //EXETAZEI AN YPARXOUN DIATHESIMES PTHSEIS
                    if(flights!=null&&flights.size()>0){
                        for(FlightBooking item:flights){    //PROSPELNAEI OLES TIS DIATHESIMES PTHSEIS ME SKOPO THN DHMIOURGIA TWN PANEL
                            oneWayPanel = new OneWayPanel(item,flightService);  //DHMIOURGEI TO PANEL GIA THN PTHSH
                            oneWayPanel.addContainerListener(new ContainerListener(){   //DHMIOURGEI ENAN CONTAINERLISTENER ME SKOPO OTAN KANEI BOOK KAPIWS STO PANEL THS ONEWAY NA DIAGRAPSEI TA PROHGOUMENA PANEL PTHSEWN KAI NA PAEI STHN ARXIKH
                                @Override
                                public void componentAdded(ContainerEvent e) {
                                }
                                @Override
                                public void componentRemoved(ContainerEvent e) {
                                    showPanel("card2"); //DEIXNEI TO ARXIKO PANEL TS ANAZHTHSH DHLADH
                                    removeAndKeep(bookingPanel, bookingTitlePanel);     //DIAGRAFEI OLA TA PANELS EKTOS APO TON TITLO
                                }
                            });
                            bookingPanel.add(oneWayPanel);   //EISAGEIT HN PTHSH STO PANEL TWN KRATHSEWN
                        }
                        showPanel("card6"); //DEIXNEI TO PANEL TWN KRATHSEWN STO FRAME
                    }
                    else{//AN DEN YPARXOUN DIATHESIMES PTHSEIS EPISTREFEI ENA MHNIMA
                        JOptionPane.showMessageDialog(searchButton.getRootPane(), "Δεν βρέθηκαν πτήσεις για αυτά τα στοιχεία", "Ενημέρωση Αναζήτησης", JOptionPane.INFORMATION_MESSAGE);

            }
            
        }   
        else if(!returnDayButton.getText().equals("Ημερολόγιο") ){ //GIA THN PERIPTWSH POU EXEI EPISTROFH KAI EXEI EPILEXTHEI MERA
            //DHMIOURGIA ANTIKEIMENOU GIA THN ANAZITISI PTHSHS  
            flight = new FlightSearchCrit(fromComboBox.getSelectedItem().toString(),
                    toComboBox.getSelectedItem().toString(),calendarDeparture.getDateS().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),
                    Integer.parseInt(passComboBox.getSelectedItem().toString()),calendarArrival.getDateS().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
           //EPIKOINWNIA ME TON SERVER  DINONTA TOU TOU TO ANTIKEIMENO POU EXEI TIS EPILOGES KAI LAMVANEI TIS PTHSEIS
            flights=flightService.searchFlights(flight);
         
            if(flights!=null&&flights.size()>0){    //AN VRETHIKAN PTHSEIS TOTE
                for(FlightBooking item:flights){    //PROSPELNAEI OLES TIS PTHSEIS
                    roundTrip  = new RoundTripPanel(item,flightService);    //FTIAXNEI NEO PANEL POU ENAI GIA TIS PTHSEIS ME EPISTROFH
                    
                    roundTrip.addContainerListener(new ContainerListener(){  //CONTAINERLISTENER GIA NA ELEXEI AN DIAGRAFTEI KAPOIO COMPONENT TOTE NA DIAGRAPSEI AUTO TO PANEL KAI NA PAEI STHN ARXIKH
                    @Override
                     public void componentAdded(ContainerEvent e) {
                    }

                    @Override
                    public void componentRemoved(ContainerEvent e) {
                        showPanel("card2");
                        removeAndKeep(bookingPanel, bookingTitlePanel);
                    }
              
                    });
                    bookingPanel.add(roundTrip);
                } 
                showPanel("card6"); //EMFANIZEI TO NEO PANEL STO FRAME
            }
            else{ //ALLIWS EIDOPOIEI TON XRHSTH OTI DEN VRETHYKE PTHSH
                JOptionPane.showMessageDialog(searchButton.getRootPane(), "Δεν βρέθηκαν πτήσεις για αυτά τα στοιχεία", "Ενημέρωση Αναζήτησης", JOptionPane.INFORMATION_MESSAGE);

            }
           
          
        }  
        } catch (RemoteException  | NullPointerException ex) {
              JOptionPane.showMessageDialog(null, "Αποτυχία Σύνδεσης Με Τον Σέρβερ Της Βάσης",null,JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_searchButtonActionPerformed
    //METHODOS GIA THN EPILOGH TOU RADIO BUTTON MONHS PTHSHS KAI KANEI TO KOUMPI GIA TO HMEROLOGIO THS EPISTROFHS NA MHN EPILEGETAI
    private void oneWayRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneWayRadioButtonActionPerformed
        isOneWay=true;  
        returnDayButton.setEnabled(false);
      
    }//GEN-LAST:event_oneWayRadioButtonActionPerformed
    //METHODOS GIA NA SETAREI TO MODELO TOU COMPO BOX TWN ONOMATWN TWN POLEWN
    private void fromComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromComboBoxActionPerformed
        toComboBox.setModel(setMod());
    }//GEN-LAST:event_fromComboBoxActionPerformed
    
    private void toComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toComboBoxActionPerformed
        
    }//GEN-LAST:event_toComboBoxActionPerformed
    //METHODOS GIA TO AN PATITHEI TO BUTTON GIA TO HMEROLOGIO THS PTHSHS ANAXWRHSHS
    private void departureDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureDayButtonActionPerformed
        if(!CalendarPopUp.isActive()){//ELEGXEI AN DEN FENETAI TO POPUP TOU HMEROLOGIOU
        returnDayButton.setText("Ημερολόγιο"); //THETEI TO TEXT TOU KOUMPIOU TOU HMEROLOGIOU THS EPISTROFHS
        calendarDeparture = new CalendarPopUp(criteriaPanel,departureDayButton,getGivenDate()); //FTIAXNEI NEO POPUP DINONTAS TO PANEL POU THA EMFANIZETAI MESW KATHWS KAI POU APO TO departureDayButton KAI THN ARXIKH MERA TOU HMEROLOGIOU
         if(!isOneWay){ //ELEGXEI AN DEN EINAI ONEWAY TOTE THETEI TO KOUMPI THS EPISTROFH ON
             returnDayButton.setEnabled(true);
         }
        
        }
    }//GEN-LAST:event_departureDayButtonActionPerformed
    //METHODOS POU ELEGXEI AN EXEI TO TEXT HMEROLOGIO GIA TO AN EXEI EISDAXTHEI H HMERA ANAXWRHSHS KAI THETEI THN HMERA EPISTROFHS
    private void returnDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnDayButtonActionPerformed
        if((!departureDayButton.getText().equals("Ημερολόγιο"))&&!CalendarPopUp.isActive()&&(!isOneWay)){
            calendarArrival = new CalendarPopUp(criteriaPanel,returnDayButton,calendarDeparture.getDateS()); //FTIAXNEI TO POPUP GIA THN EPILOGH GIA THN HMEROMHNIA ANAXWRISHS
        }
    }//GEN-LAST:event_returnDayButtonActionPerformed
    //METHODOS GIA NA EMFANIZEI TO KATALHLO PANEL STO FRAME PERNWNTAS WS ORISMA TO ONOMA THS KARTAS TOU PANEL
    private void showPanel(String card){
        cardLayout = (CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel,card);
    }
    //METHODOS GIA THN DIAXZEIRISH AN PATIOTHEI TO ITEM TOU MENIOU
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        showPanel("card2");  //EMFANIZEI TO PANEL THS ANAZHTHSHS
        removeAndKeep(bookingPanel, bookingTitlePanel); //AFAIREI OLA TA PANEL APO TO PANEL TWN KRATHSEWN EKTOS TOU TITLOU
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    //METHODOS H OPOIA YLOPOIEI TO MODELO GIA TA COMPOBOX
    //ETSI WSTE NA MHN EMFANIZETAI H IDIA EPILOGH POLHS GIA TON PROORISMO OPWS KAI THN ANAXWRHSH 
    private ComboBoxModel<String> setMod(){
        String[] temp = new String[listOfLocations.length-1];   //DHMIOURGEI ENA PINAKA STRING ME MEGETHOS MIKROTERO KATA ENA OLWN TWN POLEWN
        int count=0;
        for (String listOfLocation : listOfLocations) { //PROSPERNAEI OLES TIS POLEIS
            if (!listOfLocation.equals(fromComboBox.getSelectedItem())) {   //AN H POLH POU EXEI EPILEXTHEI DEN UPARXEI STON PINAKA
                temp[count++] = listOfLocation; //TOTE PROSTHETEI STON PINAKA THN POLH
            }
        }
        return new javax.swing.DefaultComboBoxModel<>(temp);    //EPISTEFEI TO MODELO
    }
   
    //METHODOS GIA NA DWSEI THN EPILEGMENH HMEROMHNIA
    public void setGivenDate(Date givenDate){
        this.givenDate= givenDate;
    }
    //METHODOS GIA NA EPISTREPSEI THN EPILEGMENH HMEROMHNIA
    public Date getGivenDate(){
        return givenDate;
    }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel bookingPanel;
    private javax.swing.JLabel bookingTitleLabel;
    private javax.swing.JPanel bookingTitlePanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel criteriaPanel;
    private javax.swing.JLabel departureDLabel;
    private javax.swing.JButton departureDayButton;
    private javax.swing.JComboBox<String> fromComboBox;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton oneWayRadioButton;
    private javax.swing.JComboBox<String> passComboBox;
    private javax.swing.JLabel passengersLabel;
    private javax.swing.JLabel returnDLabel;
    private javax.swing.JButton returnDayButton;
    private javax.swing.JRadioButton roundTripRadioButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel1;
    private javax.swing.JLabel searchTitle;
    private javax.swing.JComboBox<String> toComboBox;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables
}
