//DIONYSIOS THEODOSIS AM:321/2015066 2H OMADIKH KATANEMHMENA
package clientgui;

import shared.FlightService;
import java.rmi.RemoteException;
import shared.FlightBooking;
import javax.swing.JOptionPane;
import static mytools.StringDate.*;

//KLASH GIA TO PANEL PTHSEWN ME EPISTROFH
public class RoundTripPanel extends javax.swing.JPanel {
    //DILWSH PARAMETRWN KLASHS
    private final FlightBooking flight;               //PARAMETROS GIA THN KRATHSH
    private final FlightService flightService;        //PARAMETROS GIA TO SHARED INTERFACE
    
    //CONSTRUCTOR THS KLASHS ME ORISMATA THN KRATHSH KAI TO ANTIKEIMENO TOU SHARED INTERFACE
    public RoundTripPanel(FlightBooking flight,FlightService flightService) {
        this.flight=flight;
        this.flightService=flightService;
        initComponents();   //ARXIKOPOIHSH TOU PANEL
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        outboundTPanel = new javax.swing.JPanel();
        departureLabel = new javax.swing.JLabel();
        outBrouteLabel = new javax.swing.JLabel();
        returnPanel = new javax.swing.JPanel();
        returnArDatePanel = new javax.swing.JPanel();
        arivRtimeLabel = new javax.swing.JLabel();
        originAir2Label = new javax.swing.JLabel();
        returnDateLabel = new javax.swing.JLabel();
        seatsPanel = new javax.swing.JPanel();
        seat2TLabel = new javax.swing.JLabel();
        seat2Label = new javax.swing.JLabel();
        returnDeparturePanel = new javax.swing.JPanel();
        depRtimeLabel = new javax.swing.JLabel();
        returnAir2Label = new javax.swing.JLabel();
        priceTjLabel = new javax.swing.JLabel();
        pricejLabel = new javax.swing.JLabel();
        bookingjButton = new javax.swing.JButton();
        returnTPanel = new javax.swing.JPanel();
        returnLabel = new javax.swing.JLabel();
        returnRouteLabel = new javax.swing.JLabel();
        outboundPanel = new javax.swing.JPanel();
        outboundDeDajPanel = new javax.swing.JPanel();
        depOutTimeLabel = new javax.swing.JLabel();
        depOutTimeTLabel = new javax.swing.JLabel();
        outboundArDaPanel = new javax.swing.JPanel();
        outboundArTimeLabel = new javax.swing.JLabel();
        outboundArAir1Panel = new javax.swing.JLabel();
        outboundDateLabel = new javax.swing.JLabel();
        outbSeatsPanel = new javax.swing.JPanel();
        outSeatsTLabel = new javax.swing.JLabel();
        outSeatsLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(931, 436));
        setMinimumSize(new java.awt.Dimension(679, 436));

        mainPanel.setBackground(java.awt.Color.lightGray);
        mainPanel.setMaximumSize(new java.awt.Dimension(931, 383));
        mainPanel.setMinimumSize(new java.awt.Dimension(611, 384));

        outboundTPanel.setBackground(java.awt.Color.lightGray);

        departureLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        departureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        departureLabel.setText("Αναχώρηση:");

        outBrouteLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        outBrouteLabel.setText(flight.getOutboundFlight().getOrigin()+"-"+flight.getOutboundFlight().getDestination());

        javax.swing.GroupLayout outboundTPanelLayout = new javax.swing.GroupLayout(outboundTPanel);
        outboundTPanel.setLayout(outboundTPanelLayout);
        outboundTPanelLayout.setHorizontalGroup(
            outboundTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outboundTPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(departureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outBrouteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        outboundTPanelLayout.setVerticalGroup(
            outboundTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outboundTPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outboundTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outBrouteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        returnPanel.setBackground(new java.awt.Color(255, 255, 255));

        returnArDatePanel.setOpaque(false);

        arivRtimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        arivRtimeLabel.setText(flight.getReturnFlight().getDestinationAirportId());

        originAir2Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        originAir2Label.setText(flight.getReturnFlight().getArrivalDate().toLocalTime().getHour()+":"+flight.getReturnFlight().getArrivalDate().toLocalTime().getMinute());

        javax.swing.GroupLayout returnArDatePanelLayout = new javax.swing.GroupLayout(returnArDatePanel);
        returnArDatePanel.setLayout(returnArDatePanelLayout);
        returnArDatePanelLayout.setHorizontalGroup(
            returnArDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnArDatePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(originAir2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arivRtimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        returnArDatePanelLayout.setVerticalGroup(
            returnArDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnArDatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnArDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(originAir2Label)
                    .addComponent(arivRtimeLabel))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        returnDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        returnDateLabel.setText(formatDate(flight.getOutboundFlight().getDepartureDate().toLocalDate()));

        seatsPanel.setOpaque(false);

        seat2TLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seat2TLabel.setText("Θέσεις:");

        seat2Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seat2Label.setText(String.valueOf(flight.getReturnFlight().getAvailableSeats()));

        javax.swing.GroupLayout seatsPanelLayout = new javax.swing.GroupLayout(seatsPanel);
        seatsPanel.setLayout(seatsPanelLayout);
        seatsPanelLayout.setHorizontalGroup(
            seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seat2TLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seat2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seatsPanelLayout.setVerticalGroup(
            seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat2TLabel)
                    .addComponent(seat2Label)))
        );

        returnDeparturePanel.setOpaque(false);

        depRtimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depRtimeLabel.setText(flight.getReturnFlight().getOriginAirportId());

        returnAir2Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        returnAir2Label.setText(flight.getReturnFlight().getDepartureDate().getHour()+":"+flight.getReturnFlight().getDepartureDate().getMinute());

        javax.swing.GroupLayout returnDeparturePanelLayout = new javax.swing.GroupLayout(returnDeparturePanel);
        returnDeparturePanel.setLayout(returnDeparturePanelLayout);
        returnDeparturePanelLayout.setHorizontalGroup(
            returnDeparturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnDeparturePanelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(returnAir2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(depRtimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        returnDeparturePanelLayout.setVerticalGroup(
            returnDeparturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnDeparturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnDeparturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnAir2Label)
                    .addComponent(depRtimeLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout returnPanelLayout = new javax.swing.GroupLayout(returnPanel);
        returnPanel.setLayout(returnPanelLayout);
        returnPanelLayout.setHorizontalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnPanelLayout.createSequentialGroup()
                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(returnDeparturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(returnArDatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(returnPanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(returnDateLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        returnPanelLayout.setVerticalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnArDatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnDeparturePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(returnPanelLayout.createSequentialGroup()
                        .addComponent(seatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        priceTjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceTjLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceTjLabel.setText("Τιμή:");

        pricejLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pricejLabel.setText(Double.toString(flight.getPrice())+"€");
        pricejLabel.setToolTipText("");

        bookingjButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookingjButton.setText("Κάνε Κράτηση");
        bookingjButton.setFocusable(false);
        bookingjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingjButtonActionPerformed(evt);
            }
        });

        returnTPanel.setBackground(java.awt.Color.lightGray);

        returnLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        returnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnLabel.setText("Επιστροφή:");

        returnRouteLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        returnRouteLabel.setText(flight.getReturnFlight().getOrigin()+"-"+flight.getReturnFlight().getDestination());

        javax.swing.GroupLayout returnTPanelLayout = new javax.swing.GroupLayout(returnTPanel);
        returnTPanel.setLayout(returnTPanelLayout);
        returnTPanelLayout.setHorizontalGroup(
            returnTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnTPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnRouteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        returnTPanelLayout.setVerticalGroup(
            returnTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnTPanelLayout.createSequentialGroup()
                .addGroup(returnTPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnRouteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        outboundPanel.setBackground(new java.awt.Color(255, 255, 255));

        outboundDeDajPanel.setOpaque(false);

        depOutTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depOutTimeLabel.setText(flight.getOutboundFlight().getOriginAirportId());

        depOutTimeTLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depOutTimeTLabel.setText(flight.getOutboundFlight().getDepartureDate().getHour()+":"+flight.getOutboundFlight().getDepartureDate().getMinute());

        javax.swing.GroupLayout outboundDeDajPanelLayout = new javax.swing.GroupLayout(outboundDeDajPanel);
        outboundDeDajPanel.setLayout(outboundDeDajPanelLayout);
        outboundDeDajPanelLayout.setHorizontalGroup(
            outboundDeDajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outboundDeDajPanelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(depOutTimeTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(depOutTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        outboundDeDajPanelLayout.setVerticalGroup(
            outboundDeDajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outboundDeDajPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outboundDeDajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depOutTimeTLabel)
                    .addComponent(depOutTimeLabel))
                .addContainerGap())
        );

        outboundArDaPanel.setOpaque(false);

        outboundArTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        outboundArTimeLabel.setText(flight.getOutboundFlight().getDestinationAirportId());

        outboundArAir1Panel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        outboundArAir1Panel.setText(flight.getOutboundFlight().getArrivalDate().toLocalTime().getHour()+":"+flight.getOutboundFlight().getArrivalDate().toLocalTime().getMinute());

        javax.swing.GroupLayout outboundArDaPanelLayout = new javax.swing.GroupLayout(outboundArDaPanel);
        outboundArDaPanel.setLayout(outboundArDaPanelLayout);
        outboundArDaPanelLayout.setHorizontalGroup(
            outboundArDaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outboundArDaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(outboundArAir1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outboundArTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        outboundArDaPanelLayout.setVerticalGroup(
            outboundArDaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outboundArDaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outboundArDaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outboundArAir1Panel)
                    .addComponent(outboundArTimeLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        outboundDateLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        outboundDateLabel.setText(formatDate(flight.getOutboundFlight().getDepartureDate().toLocalDate()));

        outbSeatsPanel.setOpaque(false);

        outSeatsTLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        outSeatsTLabel.setText("Θέσεις:");

        outSeatsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        outSeatsLabel.setText(String.valueOf(flight.getOutboundFlight().getAvailableSeats()));

        javax.swing.GroupLayout outbSeatsPanelLayout = new javax.swing.GroupLayout(outbSeatsPanel);
        outbSeatsPanel.setLayout(outbSeatsPanelLayout);
        outbSeatsPanelLayout.setHorizontalGroup(
            outbSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outbSeatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outSeatsTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outSeatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        outbSeatsPanelLayout.setVerticalGroup(
            outbSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outbSeatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(outbSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outSeatsTLabel)
                    .addComponent(outSeatsLabel)))
        );

        javax.swing.GroupLayout outboundPanelLayout = new javax.swing.GroupLayout(outboundPanel);
        outboundPanel.setLayout(outboundPanelLayout);
        outboundPanelLayout.setHorizontalGroup(
            outboundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outboundPanelLayout.createSequentialGroup()
                .addGroup(outboundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outboundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(outboundDeDajPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(outboundArDaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outbSeatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(outboundPanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(outboundDateLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        outboundPanelLayout.setVerticalGroup(
            outboundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outboundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outboundDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(outboundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outboundArDaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outboundDeDajPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(outboundPanelLayout.createSequentialGroup()
                        .addComponent(outbSeatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outboundTPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(returnTPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(priceTjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(pricejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(bookingjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(outboundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(outboundTPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(returnTPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTjLabel)
                    .addComponent(pricejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingjButton)
                .addGap(32, 32, 32))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(outboundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(237, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //METHODOS GIA TO OTAN PATITHEI TO KOUMPI THS KRATHSHS
    private void bookingjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingjButtonActionPerformed
         try {
           String answer = flightService.bookFlight(flight);   //KALEI TON SERVER PERNWNTAS THN KRATHSH GIA NA KANEI THN KRATHSH
           if(answer.contains("Cannot invoke \"java.io.ObjectOutputStream.close()\" because \"this.output\" is null")){
                JOptionPane.showMessageDialog(null, "Η σύνδεση με τον server βάσης χάθηκε\nΑποτυχία κράτησης",null,JOptionPane.ERROR_MESSAGE);
            }
           else{
               JOptionPane.showMessageDialog(bookingjButton.getRootPane(), answer, "Ενημέρωση Κράτησης", JOptionPane.INFORMATION_MESSAGE); 
           }
        } catch (RemoteException ex) {//AN PROKIPSEI KAPIO EXCEPOTION STHN PLEURA TOU SERVER
            //AN TO EXCEPTION EINAI LOGO THS SYNDESHS
            if (ex.getMessage() != null && (ex.getMessage().contains("Connection refused") || ex.getMessage().contains("No route to host"))) {
                JOptionPane.showMessageDialog(null, "Η σύνδεση με τον server χάθηκε το πρόγραμμα θα τερματιστεί",null,JOptionPane.ERROR_MESSAGE);
                System.exit(1);
            }
            else{//AN TO EXCEPTION EINAI LOGO TO TOU OTI DEN VRETHYKE DIATHESIMH THESH
                JOptionPane.showMessageDialog(bookingjButton.getRootPane(), "Αποτυχία κράτησης\nΔεν υπάρχουν διαθέσιμες θέσεις", "Ενημέρωση Κράτησης", JOptionPane.ERROR_MESSAGE);
            }  
        }
        //DIAGRAFH TO PANEL THS KRATHSHS
        this.removeAll();
        this.revalidate();
        this.repaint();
        
    }//GEN-LAST:event_bookingjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arivRtimeLabel;
    private javax.swing.JButton bookingjButton;
    private javax.swing.JLabel depOutTimeLabel;
    private javax.swing.JLabel depOutTimeTLabel;
    private javax.swing.JLabel depRtimeLabel;
    private javax.swing.JLabel departureLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel originAir2Label;
    private javax.swing.JLabel outBrouteLabel;
    private javax.swing.JLabel outSeatsLabel;
    private javax.swing.JLabel outSeatsTLabel;
    private javax.swing.JPanel outbSeatsPanel;
    private javax.swing.JLabel outboundArAir1Panel;
    private javax.swing.JPanel outboundArDaPanel;
    private javax.swing.JLabel outboundArTimeLabel;
    private javax.swing.JLabel outboundDateLabel;
    private javax.swing.JPanel outboundDeDajPanel;
    private javax.swing.JPanel outboundPanel;
    private javax.swing.JPanel outboundTPanel;
    private javax.swing.JLabel priceTjLabel;
    private javax.swing.JLabel pricejLabel;
    private javax.swing.JLabel returnAir2Label;
    private javax.swing.JPanel returnArDatePanel;
    private javax.swing.JLabel returnDateLabel;
    private javax.swing.JPanel returnDeparturePanel;
    private javax.swing.JLabel returnLabel;
    private javax.swing.JPanel returnPanel;
    private javax.swing.JLabel returnRouteLabel;
    private javax.swing.JPanel returnTPanel;
    private javax.swing.JLabel seat2Label;
    private javax.swing.JLabel seat2TLabel;
    private javax.swing.JPanel seatsPanel;
    // End of variables declaration//GEN-END:variables
}
