//DIONYSIOS THEODOSIS AM:321/2015066 1H OMADIKH ERGASIA
package clientapp;

import java.awt.CardLayout;
import java.awt.Toolkit;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.Socket;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.JOptionPane;

//KLASH TOY MAINFRAME TO OPOIO FTIAXNEI TO GUI KAI EPISHS STELNEI MESW SOCKET DEDOMENA STON SERVER
public class MainFrame extends javax.swing.JFrame {
   //DILWSH METAVLITWN KLASHS
   private DataOutputStream output; //GIA TO OUPUT STREAM TOU SOCKET 
   private DataInputStream input;//GIA TO INPUT STREAM TOU SOCKET
   private Socket client;//TO SOCKET
   private String fileName;//GIA TO ONOMA TOU ARXEIOY
   private Toolkit thekit; //DHMIOURGEIA WSTE NA MAS VOITHISEI GIA THN EIKONA TOU FRAME
   
   //CONSTRUCTOR THS KLASHS O OPOIOS DHMIOURGEI TO FRAME KAI KALH KAI OLES TIS APARAITHTES METHODOUS GIA THN EPIKOINWNIA CLIENT SERVER
   public MainFrame() {
        thekit = this.getToolkit();
        //EISAGWGH EIKONAS STO FRAME
        this.setIconImage(thekit.getImage(".\\src\\icons\\frameIcon.png"));
        //DHMIOURGEIA TOU FRAME
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        homejLabel = new javax.swing.JLabel();
        homejScrollPane = new javax.swing.JScrollPane();
        homeTextArea = new javax.swing.JTextArea();
        newFilePanel = new javax.swing.JPanel();
        newFjLabel = new javax.swing.JLabel();
        newFjScrollPane = new javax.swing.JScrollPane();
        newFTextArea1 = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        downFpanel = new javax.swing.JPanel();
        downjLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        downFTextField = new javax.swing.JTextField();
        downFButton = new javax.swing.JButton();
        downjScrollPane = new javax.swing.JScrollPane();
        downTextArea = new javax.swing.JTextArea();
        deleteFpanel = new javax.swing.JPanel();
        deletejLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        delFTextField = new javax.swing.JTextField();
        delFButton = new javax.swing.JButton();
        insertFpanel = new javax.swing.JPanel();
        insertjLabel = new javax.swing.JLabel();
        insertScrollPane = new javax.swing.JScrollPane();
        insertFTextArea = new javax.swing.JTextArea();
        insertFButton = new javax.swing.JButton();
        insertClrButton1 = new javax.swing.JButton();
        appendFpanel = new javax.swing.JPanel();
        appendjLabel = new javax.swing.JLabel();
        appendjScrollPane = new javax.swing.JScrollPane();
        annexFTextArea = new javax.swing.JTextArea();
        appendFButton = new javax.swing.JButton();
        appendClrButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        HomeMenuItem = new javax.swing.JMenuItem();
        newFMenuItem = new javax.swing.JMenuItem();
        downFMenuItem = new javax.swing.JMenuItem();
        delFMenuItem = new javax.swing.JMenuItem();
        insertFMenuItem = new javax.swing.JMenuItem();
        modifyFMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Απομακρυσμένη Διαχείρηση txt");

        mainPanel.setLayout(new java.awt.CardLayout());

        homejLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        homejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homejLabel.setText("Αρχική");
        homejLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        homejScrollPane.setBorder(null);
        homejScrollPane.setOpaque(false);

        homeTextArea.setEditable(false);
        homeTextArea.setColumns(20);
        homeTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        homeTextArea.setLineWrap(true);
        homeTextArea.setRows(5);
        homeTextArea.setText("\tΠρόγραμμα επεξεργασίας αρχείων txt ,που είναι αποθυκευμένα στον Server.\n\n- Δημιουργία αρχείου και αποθύκευση στον φάκελο του συνδεδεμένου Server.\n- Λήψη του αρχείου βάση του καθορισμένου ονόματος του και προβολή των περιεχομένων.\n- Διαγραφή του αρχείου απο τον Server βάση του επιλεγμένου ονόματος.\n- Εισαγωγή περιεχομένου στο καθορισμένο αρχείο βάση ονόματος στον Server και υπερκάλυψη του περιεχομένου του.\n- Εισαγωγή του περιεχομένου στο τέλος του καθορισμένου αρχείο βάση ονόματος στον Server.\n\nΓια τις παραπάνω λειτουργίες διατρέξτε στο μενού.");
        homeTextArea.setWrapStyleWord(true);
        homeTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Σχετικά με την εφαρμογή", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        homeTextArea.setOpaque(false);
        homejScrollPane.setViewportView(homeTextArea);

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                        .addGap(0, 110, Short.MAX_VALUE)
                        .addComponent(homejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(homejScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        mainPanel.add(HomePanel, "card7");

        newFjLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newFjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newFjLabel.setText("Δημιουργία Νέου Αρχείου");
        newFjLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newFTextArea1.setColumns(20);
        newFTextArea1.setRows(5);
        newFjScrollPane.setViewportView(newFTextArea1);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/data_upload.png"))); // NOI18N
        saveButton.setContentAreaFilled(false);
        saveButton.setFocusable(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newFilePanelLayout = new javax.swing.GroupLayout(newFilePanel);
        newFilePanel.setLayout(newFilePanelLayout);
        newFilePanelLayout.setHorizontalGroup(
            newFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newFjScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newFjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newFilePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        newFilePanelLayout.setVerticalGroup(
            newFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newFjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newFjScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addGap(4, 4, 4))
        );

        mainPanel.add(newFilePanel, "card2");

        downjLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        downjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        downjLabel.setText("Λήψη Αρχείου");
        downjLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setText("Καταχώρηση ονόματος αρχείου:");

        downFButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/download_file.png"))); // NOI18N
        downFButton.setContentAreaFilled(false);
        downFButton.setFocusable(false);
        downFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downFButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(downFButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(downFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        downTextArea.setColumns(20);
        downTextArea.setRows(5);
        downjScrollPane.setViewportView(downTextArea);
        downTextArea.setEditable(false);

        javax.swing.GroupLayout downFpanelLayout = new javax.swing.GroupLayout(downFpanel);
        downFpanel.setLayout(downFpanelLayout);
        downFpanelLayout.setHorizontalGroup(
            downFpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, downFpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(downFpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(downjScrollPane)
                    .addComponent(downjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        downFpanelLayout.setVerticalGroup(
            downFpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downFpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(downjLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downjScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(downFpanel, "card3");

        deletejLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deletejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletejLabel.setText("Διαγραφή Αρχείου");
        deletejLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setText("Καταχώρηση ονόματος αρχείου:");

        delFButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/file_delete.png"))); // NOI18N
        delFButton.setContentAreaFilled(false);
        delFButton.setFocusable(false);
        delFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delFButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(delFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(delFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout deleteFpanelLayout = new javax.swing.GroupLayout(deleteFpanel);
        deleteFpanel.setLayout(deleteFpanelLayout);
        deleteFpanelLayout.setHorizontalGroup(
            deleteFpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteFpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteFpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(deleteFpanelLayout.createSequentialGroup()
                        .addGap(0, 274, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 274, Short.MAX_VALUE)))
                .addContainerGap())
        );
        deleteFpanelLayout.setVerticalGroup(
            deleteFpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteFpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deletejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );

        mainPanel.add(deleteFpanel, "card4");

        insertjLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        insertjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insertjLabel.setText("Προσθήκη περιεχομένου");
        insertjLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        insertFTextArea.setColumns(20);
        insertFTextArea.setRows(5);
        insertScrollPane.setViewportView(insertFTextArea);

        insertFButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/data_upload.png"))); // NOI18N
        insertFButton.setContentAreaFilled(false);
        insertFButton.setFocusable(false);
        insertFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertFButtonActionPerformed(evt);
            }
        });

        insertClrButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/text_clear.png"))); // NOI18N
        insertClrButton1.setToolTipText("Διαγραφή περιεχομένου κειμενογράφου");
        insertClrButton1.setContentAreaFilled(false);
        insertClrButton1.setFocusable(false);
        insertClrButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertClrButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertFpanelLayout = new javax.swing.GroupLayout(insertFpanel);
        insertFpanel.setLayout(insertFpanelLayout);
        insertFpanelLayout.setHorizontalGroup(
            insertFpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertFpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertFpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertFpanelLayout.createSequentialGroup()
                        .addComponent(insertClrButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(insertScrollPane)
                    .addComponent(insertjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertFpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(insertFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        insertFpanelLayout.setVerticalGroup(
            insertFpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertFpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insertClrButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(insertScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertFButton)
                .addGap(13, 13, 13))
        );

        mainPanel.add(insertFpanel, "card5");

        appendjLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        appendjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appendjLabel.setText("Προσάρτηση περιεχομένου");
        appendjLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        annexFTextArea.setColumns(20);
        annexFTextArea.setRows(5);
        appendjScrollPane.setViewportView(annexFTextArea);

        appendFButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/data_upload.png"))); // NOI18N
        appendFButton.setContentAreaFilled(false);
        appendFButton.setFocusable(false);
        appendFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appendFButtonActionPerformed(evt);
            }
        });

        appendClrButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/text_clear.png"))); // NOI18N
        appendClrButton.setToolTipText("Διαγραφή περιεχομένου κειμενογράφου");
        appendClrButton.setContentAreaFilled(false);
        appendClrButton.setFocusable(false);
        appendClrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appendClrButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout appendFpanelLayout = new javax.swing.GroupLayout(appendFpanel);
        appendFpanel.setLayout(appendFpanelLayout);
        appendFpanelLayout.setHorizontalGroup(
            appendFpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appendFpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appendFpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appendjScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(appendjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                    .addGroup(appendFpanelLayout.createSequentialGroup()
                        .addComponent(appendClrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appendFpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(appendFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        appendFpanelLayout.setVerticalGroup(
            appendFpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appendFpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appendjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appendClrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appendjScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appendFButton)
                .addContainerGap())
        );

        mainPanel.add(appendFpanel, "card6");

        jMenu1.setText("Μενού");

        HomeMenuItem.setText("Αρχική");
        HomeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(HomeMenuItem);

        newFMenuItem.setText("Νέο Αρχείο");
        newFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(newFMenuItem);

        downFMenuItem.setText("Λήψη Αρχείου");
        downFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downFMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(downFMenuItem);

        delFMenuItem.setText("Διαγραφή Αρχείου");
        delFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delFMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(delFMenuItem);

        insertFMenuItem.setText("Προσθήκη περιεχομένου");
        insertFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertFMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(insertFMenuItem);

        modifyFMenuItem.setText("Προσάρτηση περιεχομένου");
        modifyFMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyFMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(modifyFMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //SYNARTISH H OPOIA AN PATHTHEI TO NEO ARXEIO STO MENU NA EMFANIZEI TO KATALHLO PANEL
    private void newFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFMenuItemActionPerformed
        CardLayout cl = (CardLayout) (mainPanel.getLayout());
        cl.show(mainPanel, "card2");
        setVisible(true);
    }//GEN-LAST:event_newFMenuItemActionPerformed
    //SYNARTISEI GIA TO AN PATITHEI H DIAGRAFH STO PANEL THS DIAGRAFHS
    private void downFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downFButtonActionPerformed
        if(!downFTextField.getText().equals("")){//AN EXEI DWSEI ONOMA ARXEIOY O XRHSTHS
            runClient("DOWNLOAD_FILE");//DHMIOURGEIA SYNDESHS KAI EISAGWGH THS ENTOLHS
        } 
        else{//ALLIWS PROVALH KATALLHLO MINIMA GIA THN EISAGWGH TOU ONOMATOS TOU ARXEIOU
            JOptionPane.showMessageDialog(this,"Πρέπει να γράψεις όνομα αρχείου");
        }
    }//GEN-LAST:event_downFButtonActionPerformed
    //METHODOS GIA TO AN O XRHSTHS EXEI EPILEXEI APO TO MENOU LIPSI GIA THN EMFANISH TOU PANEL THS LIPSIS
    private void downFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downFMenuItemActionPerformed
        CardLayout cl = (CardLayout) (mainPanel.getLayout());//PERNEI TO LAYOUT TOU MAINPANEL KAI TO ORIZEI STHN METAVLITH CARDLAYOUT
        cl.show(mainPanel, "card3");//KAI EMFANISH TOU PANEL THS LIPSIS STO MAINPANEL
        setVisible(true);//EMFANISH TOU FRAME
    }//GEN-LAST:event_downFMenuItemActionPerformed
    //METHODOS GIA TO AN O XRHSTHS EXEI EPILEXEI APO TO MENOU DIAGRAFH GIA THN EMFANISH TOU PANEL THS DIAGRAFHS
    private void delFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delFMenuItemActionPerformed
        CardLayout cl = (CardLayout) (mainPanel.getLayout());
        cl.show(mainPanel, "card4");
        setVisible(true);
    }//GEN-LAST:event_delFMenuItemActionPerformed
    //METHODOS GIA TO AN O XRHSTHS EXEI EPILEXEI APO TO MENOU PROSTHIKI GIA THN EMFANISH TOU PANEL THS PROSTHIKIS
    private void insertFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertFMenuItemActionPerformed
        CardLayout cl = (CardLayout) (mainPanel.getLayout());
        cl.show(mainPanel, "card5");
        setVisible(true);
    }//GEN-LAST:event_insertFMenuItemActionPerformed
    //METHODOS GIA TO AN O XRHSTHS EXEI EPILEXEI APO TO MENOU PROSARTISH GIA THN EMFANISH TOU PANEL THS PROSARTISHS
    private void modifyFMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyFMenuItemActionPerformed
        CardLayout cl = (CardLayout) (mainPanel.getLayout());
        cl.show(mainPanel, "card6");
        setVisible(true);
    }//GEN-LAST:event_modifyFMenuItemActionPerformed
    //SYNARTISH GIA OTAN PATITHEI TO KOUMPI POU YPARXEI STO PANEL THS PROSARTISHS 
    private void appendFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appendFButtonActionPerformed
        if(!annexFTextArea.getText().equals("")){//AN EXEI GRAPSEI O XRHSTHS PERIEXOMENO
            try{//XRHSIMOPOIHSH TRY CATCH GIA TO AN O XRHSTHS AKURWSH THN APOSTOLH
                //AN EXEI DWSEI ONOMA O XRHSTHS
                if(!(fileName = JOptionPane.showInputDialog(this, "Καταχώρησε το όνομα του αρχείου","Προσάρτηση περιεχομένου",JOptionPane.PLAIN_MESSAGE)).equals("")){
                    runClient("APPEND_CONTENT");//DHMIOURGEIA SUNDESHS ME TON SERVER KAI PAREXONTAS THN KATALHLH ENTOLH
                }
                else{//ALLIWS AN DEN EXEI DWSEI ONOMA TOTE MINIMA GIA THN EISAGWGH ONOMATOS
                    JOptionPane.showMessageDialog(this,"Πρέπει να γράψεις το όνομα του αρχείου πρώτα");
                }
            }
            catch(NullPointerException e){//AN EPISTREPSEI STHN THESH TOU ONOMATOS NULL SE PERIPTWSH POU PATHSEI CANCEL H KLEISH TO DIALOG
                //TIPOTA GT DEN XREIAZOMASTE ENHMERWSH
            }
        }
        else{//ALLIWS MINIMA GIA NA IDOPOIHSH TON XRHSTH
            JOptionPane.showMessageDialog(this,"Πρέπει να γράψεις περιεχόμενο πρώτα");
        }    
    }//GEN-LAST:event_appendFButtonActionPerformed
    //SYNARTISH GIA OTAN PATITHEI TO KOUMPI POU YPARXEI STO PANEL THS PROSTHIKIS
    private void insertFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertFButtonActionPerformed
        if(!insertFTextArea.getText().equals("")){//AN EXEI GRAPSEI PERIEXOMENA STHN TEXTAREA 
            try{//ELEGXEI GIA TO AN TO FILENAME GINEI NULL KAI EGIREI EXERESH
                //AN EXEI GRAPSEI O XRHSTHS ONOMA ARXEIOU
                if(!(fileName = JOptionPane.showInputDialog(this, "Καταχώρησε το όνομα του αρχείου","Προσθήκη περιεχομένου",JOptionPane.PLAIN_MESSAGE)).equals("")){
                    runClient("INSERT_CONTENT");//KALH THN RUNCLIENT GIA THN DIMIOURGEIA SYNDESHS KAI EISAGWGH THS KATALHLHS ENTOLHS
                }
                else{
                    JOptionPane.showMessageDialog(this,"Πρέπει να γράψεις το όνομα του αρχείου πρώτα");
                }
            }
            catch(NullPointerException e){
                //TIPOTA GT MPOREI NA EXEI PATISEI CANCEL H NA EKLEISE TO DIALOG O XRHSTHS
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Πρέπει να γράψεις περιεχόμενο πρώτα");
        }
    }//GEN-LAST:event_insertFButtonActionPerformed
    //METHODOS GIA TO AN O XRHSTHS EXEI EPILEXEI APO TO MENOU ARXIKH GIA THN EMFANISH TOU PANEL THS ARXIKHS
    private void HomeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeMenuItemActionPerformed
        CardLayout cl = (CardLayout) (mainPanel.getLayout());
        cl.show(mainPanel, "card7");
        setVisible(true);
    }//GEN-LAST:event_HomeMenuItemActionPerformed
    //SYNARTISH GIA OTAN PATITHEI TO KOUMPI POU YPARXEI STO PANEL TOU NEOU ARXEIOU 
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(!newFTextArea1.getText().equals("")){//ELEXGEI AN EXEI GRAPSEI KEIMENO
            try{//DIAXEIRISH THS EXERAISEIS AN EPISTREPSEI NULL STO FILENAME 
                //ELEGXEI AN EXEI DWSEI ONOMA O XRHSTHS
                if(!(fileName = JOptionPane.showInputDialog(this, "Καταχώρησε το όνομα του αρχείου","Αποθύκευση αρχείου",JOptionPane.PLAIN_MESSAGE)).equals("")){
                    runClient("NEW_FILE");//TOTE KALH THN SYNARTISEI GIA THN DIMIOURGIA SYNDESHS
                }
                else{
                    JOptionPane.showMessageDialog(this,"Πρέπει να γράψεις το όνομα του αρχείου πρώτα");
                }
            }
            catch(NullPointerException e){
                //TIPOTA GT MPOREI NA EXEI PATISEI CANCEL H NA EKLEISE TO DIALOG O XRHSTHS
            }
        } 
        else{
            JOptionPane.showMessageDialog(this,"Πρέπει να γράψεις περιεχόμενο πρώτα");
        }
    }//GEN-LAST:event_saveButtonActionPerformed
    //SYNARTISH GIA OTAN PATITHEI TO KOUMPI POU YPARXEI STO PANEL THS DIAGRAFHS GIA DIAGRAFH
    private void delFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delFButtonActionPerformed
        //ELEGXEI AN EXEI DWSEI O XRHSTHS ONOMA
        if(!delFTextField.getText().equals("")){
            runClient("DELETE_FILE");//KALH GIA DHMIOURGEIA SYNDESHS
        } 
        else{
            JOptionPane.showMessageDialog(this,"Γράψε όνομα αρχείου");
        }
    }//GEN-LAST:event_delFButtonActionPerformed
    //SYNARTISH GIA TO AN PATITHEI TO KOUMPI THS EKATHARRISHS STO PANEL THS PROSARTISHS
    private void appendClrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appendClrButtonActionPerformed
        annexFTextArea.setText("");//KANEI TO KEIMENO ME KENO
    }//GEN-LAST:event_appendClrButtonActionPerformed
    //SYNARTISH GIA TO AN PATITHEI TO KOUMPI THS EKATHARRISHS STO PANEL THS PROSTHIKIS
    private void insertClrButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertClrButton1ActionPerformed
       insertFTextArea.setText("");//KANEI TO KEIMENO ME KENO
    }//GEN-LAST:event_insertClrButton1ActionPerformed
    //SYNARTISH GIA THN EKTELESH THS SYNDESHS TOU SOCKET ME TON SERVER
    private void runClient(String command){//PERNEI SAN ORISMA THN EPILOGH APO TON XRHSTH
    try{//GIA NA PIASEI TIS EXERESEIS
        connectToServer();//KALESMA THS SYNARTISHS GIA THN DHMIOURGIA SYNDESH ME TON SERVER
        getStreams(); //KALESMA THS SYNARTISHS GIA NA DHMIOURGHSEI TA DATASTREAMS
        processConnections(command); //SYNARTISH GIA THN METAFORA TWN DEDOMENW APO PELATH SE SERVER ANALOGA ME TO TI EXEI EPILEXH
    }
    catch(EOFException eofException){//AN VREI TO END OF FILE TOTE EMFANISEI TOU MINIMATOS
        displayMessage("\nClient Terminated Connection\n"); 
    }
    catch(IOException ioException){//AN H EXERESEI EINAI IO
        ioException.printStackTrace();
    }
    finally{//TELOS KLEINEI TO SOCKET 
        closeConnection();//KALSEMA THS SYNARTISH GIA TON TERMATISMO THS SYNDESHS
    }
}
    //SYNDESH GIA TO KLEISIMO THS SYNDESHS
    private void closeConnection() {
       displayMessage("\nClosing Connection\n");//EMFANISH MINIMATOS KLEISIMATOS
       try{//ELEGXOS GIA KAPOIA EXERESEI IO
           output.close();//KLEINEI TO DATAOUTPUTSTREAM 
           input.close();//KLEINEI TO DATAINPUTSTREAM 
           client.close();//KLEINEI TO SOCKET
       }
       catch(IOException ioException){
           ioException.printStackTrace();
       }
    }
    //SYNARTISH GIA THN DIMIOURGIA SYNDESHS
    private void connectToServer() throws IOException {
        displayMessage("Attemping Connection\n");//EMFANISHS MINIMATOS 
        client = new Socket("localhost",9999);//DIMIOURGIA TOU SOCKET STO TOPICO SERVER KAI PORTA 9999
        displayMessage("Connected to: "+client.getInetAddress().getHostName());//EMFANIZEI TO HOSTNAME TOU SERVER
    }
    //SYNARTISH GIA THN ARXIKOPOIHSH TWN STREAMS
    private void getStreams() throws IOException {
     output = new DataOutputStream(client.getOutputStream()); //ARXIKOPOIHSH TOU DATAOUPUTSTREAM
     output.flush();
     input =  new DataInputStream(client.getInputStream());//ARXIKOPOIHSH TOU DATAOUPUTSTREAM
     displayMessage("\nGot I/O Streams\n");
    }
    //SYNARTISI GIA THN DIAXEIRH THS APARAITHTS ENERGEIAS KAI ANTALAGHS ME TON SERVER
    private void processConnections(String choice) throws IOException{
        String command;//METAVLITI GIA THN ENTOLH POU THA PREPEI NA DWSEI O CLIENT STON SERVER
        String fileContent;//METAVLITI POU EXEI TO PERIEXOMENO TOU ARXEIOU
        String message;//METAVLITI GIA TO MINIMA POU THA APOSTEILEI STON SERVER
        byte[] utf8Bytes;// PINAKAS BYTE 
        //EPILOGH SYMFWNA ME THN EPILOGH TOU XRISTI
        switch (choice){
            case "NEW_FILE" -> {//AN EINAI NEO ARXEIO
                command = "NEW_FILE";
                fileContent = newFTextArea1.getText();//PERNEI TO PERIXEOMENO KAI TO VAZEI STHN METAVLITI
                message = command + " " + fileName;//FTIAXNEI TO PRWTO MINIMA POU THA STEILEI STON SERVER ME THN ENTOLH KAI TO ONOMA TOU ARXEIOU
                utf8Bytes = fileContent.getBytes(StandardCharsets.UTF_8); //METAPAIRNEI TA BYTES APO THN METAVLITI TOU PERIEXOMENOU
                output.writeUTF(message);//STELNEI TO MINIMA
                output.writeInt(utf8Bytes.length);//STELNEI TO MEGETHOS TOU PINAKA
                output.write(utf8Bytes);//STELNEI TON PINAKA
                //DIAVAZEI APO TON SERVER
                command = input.readUTF();
                switch(command){//ANALOGA ME TO TI EXEI STEILEI O SERVER
                    case "FILE_EXISTS" -> JOptionPane.showMessageDialog(this,"Το αρχείο υπάρχει ήδη");
                    case "FILE_SAVED" -> {
                        JOptionPane.showMessageDialog(this,"Το αρχείο αποθηκεύτηκε");
                        newFTextArea1.setText("");
                    }
                    case "UPLOAD_FILE_FAILED" -> JOptionPane.showMessageDialog(this,"Αποτυχία στο ανέβασμα του αρχείου");
                }
           }

            //AN EINAI GIA NA DIAGRAPSEI ARXEIO
            case "DELETE_FILE" -> {
                output.writeUTF("DELETE"+" "+ delFTextField.getText());//STELNEI STON SERVER WS DATAOUTPUT TO DELETE KAI TO ONOMA ARXEIOU 
                output.flush();
               
                command = input.readUTF();//DIAVAZEI APO TON SERVER
                switch(command){//KAI ANALOGA EPILEGEI
                    case "FILE_NOT_FOUND" -> JOptionPane.showMessageDialog(this,"Δεν βρέθηκε αρχείο με αυτό το όνομα");
                    case "FILE_DELETED" -> JOptionPane.showMessageDialog(this,"Το αρχείο διαγράφτηκε με επιτυχία");
                       
                    case "FAILED_TO_DELETE" -> JOptionPane.showMessageDialog(this,"Παρουσιάστηκε σφάλμα κατα την διαγραφή του αρχείου");
                }
           }
            //AN EINAI GIA KATEVASMA KAI EMFANISH TOU ARXEIOU
            case "DOWNLOAD_FILE" -> {
                output.writeUTF("DOWNLOAD_FILE"+" "+downFTextField.getText());//STELNEI STON SERVER WS DATAOUTPUT THN ENTOH WS STRING KAI TO ONOMA TOU ARXEIOU
                output.flush();
                
                command = input.readUTF();//DIAVAZEI APO TON SERVER
                switch(command){
                    case "FILE_DOWNLOADED" -> {//AN PAREI THN ENTOLH APO TON SERVER OTI NA TO KATEVASEI TOTE
                        File newFile = new File(downFTextField.getText()+".txt");//DHMIOURGEI NEO ARXEIO ME TO ONOMA TOU ARXEIOU STON SERVER
                       
                        byte[] buffer = new byte[1024];//FTIAXNEI ENAN PINAKA BYTE GIA THN APOTHYKEYSH TWN BYTES APO TO STREAM 
                        
                        InputStream inputStream = client.getInputStream();//DHMIOURGEIA ITPUTSTREAM ANTIKEIMENOU
                        FileOutputStream fileOutputStream = new FileOutputStream(newFile);//DHMIOURGEIA OUTPUT STREAM GIA THN EGRAFH TOU ARXEIOU
                        inputStream.read(buffer,0,buffer.length);//DIAVASMA TOU ARXEIOU
                        fileOutputStream.write(buffer,0,buffer.length);//APOTHYKEUSH TOU ARXEIOU
                        fileOutputStream.close();//KLEISIMO TOU OUPUTSTREAM
                        inputStream.close();//KLEISIMO TOU ITPUT STREAM
                        String content="";//DIMIOURGIA METAVLTIS GIA TO KEIMENO TOU ARXEIOU
                        try {//ELEGXEI GIA KAPOIO IO EXCEPTION PANE STO DIAVASMA TOU ARXEIOU AN DEN YPARXEI PX
                            content = new String(Files.readAllBytes(Paths.get(newFile.getAbsolutePath())));//APOTHYKEYH TO PERIEXOMENO TOU ARXEIOU STHN METAVLITI
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                        downTextArea.setText(content);//PROSTHETEI TO KEIMENO STO TEXTAREA
                        JOptionPane.showMessageDialog(this,"Το αρχείo κατέβηκε με επιτυχία");//EMFANISH MINIMATOS EPITYXIAS
                }
                    case "FAILED_TO_DOWNLOAD" -> JOptionPane.showMessageDialog(this,"Παρουσιάστηκε σφάλμα κατα την λήψη του αρχείου");
                    case "FILE_NOT_FOUND" -> JOptionPane.showMessageDialog(this,"Δεν βρέθηκε αρχείο με αυτό το όνομα");
                }
           }
            //GIA THN EPILOGH PROSTHIKIS
            case "INSERT_CONTENT" -> {
                command = "INSERT_CONTENT";
                fileContent = insertFTextArea.getText();
                message = command + " " + fileName;
                utf8Bytes = fileContent.getBytes(StandardCharsets.UTF_8);//METATREPEI TO ALFARITHIMITO SE UTF8BYTES KAK TA PERNEI STHN METAVLITI
                output.writeUTF(message);//STELNEI THN ENTOLH KAI TO ONOMA TOU ARXEIOU STON SERVER
                output.writeInt(utf8Bytes.length);//STELNEI TO MEGETHOS TOU PINAKA TWN BYTES
                output.write(utf8Bytes);//KAI STELNEI TON PINAKA
                command = input.readUTF();//DIAVAZEI APO TON SERVER GIA TO APOTELESMA
                switch(command){
                    case "FILE_NOT_FOUND" -> JOptionPane.showMessageDialog(this,"Δεν βρέθηκε αρχείο με αυτό το όνομα");
                    case "INSERTION_SUCCESFUL" -> JOptionPane.showMessageDialog(this,"Επιτυχής προσθήκη περιεχομένου  στο αρχείο");
                    case "INSERTION_UNSUCCESFUL" -> JOptionPane.showMessageDialog(this,"Αποτυχία στην προσθήκη του κειμένου στο αρχείο");
                }
           }
            //GIA THN EPILOGH PROSARTISIS
            case "APPEND_CONTENT" -> {
                
                command = "APPEND_CONTENT";
                fileContent = annexFTextArea.getText();
                message = command + " " + fileName;
                utf8Bytes = fileContent.getBytes(StandardCharsets.UTF_8);
                output.writeUTF(message);
                output.writeInt(utf8Bytes.length);
                output.write(utf8Bytes);
                command = input.readUTF();
                switch(command){
                    case "FILE_NOT_EXISTS" -> JOptionPane.showMessageDialog(this,"Το αρχείο δεν υπάρχει");
                    case "APPEND_SUCCESFUL" -> JOptionPane.showMessageDialog(this,"Το κείμενο προσαρτήθηκε επιτυχώς στο αρχείο");
                    case "APPEND_UNSUCCESFUL" -> JOptionPane.showMessageDialog(this,"Αποτυχία στην προσάρτηση του κειμένου στο αρχείο");
                }
           }
        }          
    }
    //SYNARTISH GIA THN EMFANISH TOU MINIMATOS
    private void displayMessage(String message) {
       System.out.println("\n"+message);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem HomeMenuItem;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JTextArea annexFTextArea;
    private javax.swing.JButton appendClrButton;
    private javax.swing.JButton appendFButton;
    private javax.swing.JPanel appendFpanel;
    private javax.swing.JLabel appendjLabel;
    private javax.swing.JScrollPane appendjScrollPane;
    private javax.swing.JButton delFButton;
    private javax.swing.JMenuItem delFMenuItem;
    private javax.swing.JTextField delFTextField;
    private javax.swing.JPanel deleteFpanel;
    private javax.swing.JLabel deletejLabel;
    private javax.swing.JButton downFButton;
    private javax.swing.JMenuItem downFMenuItem;
    private javax.swing.JTextField downFTextField;
    private javax.swing.JPanel downFpanel;
    private javax.swing.JTextArea downTextArea;
    private javax.swing.JLabel downjLabel;
    private javax.swing.JScrollPane downjScrollPane;
    private javax.swing.JTextArea homeTextArea;
    private javax.swing.JLabel homejLabel;
    private javax.swing.JScrollPane homejScrollPane;
    private javax.swing.JButton insertClrButton1;
    private javax.swing.JButton insertFButton;
    private javax.swing.JMenuItem insertFMenuItem;
    private javax.swing.JTextArea insertFTextArea;
    private javax.swing.JPanel insertFpanel;
    private javax.swing.JScrollPane insertScrollPane;
    private javax.swing.JLabel insertjLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem modifyFMenuItem;
    private javax.swing.JMenuItem newFMenuItem;
    private javax.swing.JTextArea newFTextArea1;
    private javax.swing.JPanel newFilePanel;
    private javax.swing.JLabel newFjLabel;
    private javax.swing.JScrollPane newFjScrollPane;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
